name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test

    - name: Push to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo "$SSH_KEY" > key.pem
        chmod 400 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@$EC2_HOST <<EOF
          cd machine_learning_app/AWSAppMLOpsTemplate/
          git pull

    - name: Build and Run App
      run: |
        make build