name: Deploy to AWS ECR and Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          make install
      - name: Lint with pylint
        run: |
          make lint
      - name: Test with pytest
        run: |
          make test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Format with black
        run: |
          make format
      
      # important: configure github secrets for AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION_ECR, AWS_REGISTRY_ID, ECR_REPOSITORY, EB_ENVIRONMENT
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION_ECR }}
      
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.AWS_REGISTRY_ID }}.dkr.ecr.${{ secrets.AWS_REGION_ECR }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
      
      - name: Deploy to EB
        run: |
          EB_APP=aws_ml_app # update this to your EB application name
          EB_ENV=${{ secrets.EB_ENVIRONMENT }}
          VERSION_LABEL=$(git rev-parse --short HEAD)
          aws elasticbeanstalk create-application-version --application-name $EB_APP --version-label $VERSION_LABEL --source-bundle S3Bucket="docker-run",S3Key="Dockerrun.aws.json" # update to S3 bucket name
          aws elasticbeanstalk update-environment --environment-name $EB_ENV --version-label $VERSION_LABEL